name: humm_error_handler
description: "A comprehensive Flutter error handling library that provides centralized error tracking, logging, storage and display capabilities."
version: 0.2.0
homepage: https://github.com/hummlab/humm_error_handler

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  fimber: ">=0.6.0 <0.8.0"      
  flutter:
    sdk: flutter
  shared_preferences: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
